from sqlalchemy import select

from app.extensions import db
from app.models import NormalizedJobPosting
from app.repositories.skill_radar_repository import role_key


JOB_CATALOG = [
    {
        "external_id": "seed-backend-1",
        "title": "Backend Engineer",
        "role_name": "Backend Engineer",
        "company_name": "Harbor Labs",
        "company_size": "mid_market",
        "company_type": "product",
        "locations": ["Singapore"],
        "work_arrangement": "hybrid",
        "job_type": "full_time",
        "industries": ["technology", "fintech"],
        "seniority_level": "mid",
        "years_experience_min": 2,
        "years_experience_max": 4,
        "salary_min": 85000,
        "salary_max": 110000,
        "salary_currency": "SGD",
        "salary_period": "annual",
        "normalized_skills": ["Python", "SQL", "PostgreSQL", "REST APIs", "Docker", "AWS"],
        "core_skills": ["Python", "SQL", "REST APIs", "Docker"],
        "preferred_skills": ["PostgreSQL", "AWS", "System Design"],
        "description_summary": "Build backend APIs and data services for a fintech platform.",
        "source": "seed",
        "source_url": "https://example.com/jobs/seed-backend-1",
    },
    {
        "external_id": "seed-backend-2",
        "title": "Senior Backend Platform Engineer",
        "role_name": "Backend Engineer",
        "company_name": "Northstar Cloud",
        "company_size": "enterprise",
        "company_type": "product",
        "locations": ["Remote", "Singapore"],
        "work_arrangement": "remote",
        "job_type": "full_time",
        "industries": ["technology"],
        "seniority_level": "senior",
        "years_experience_min": 5,
        "years_experience_max": 8,
        "salary_min": 120000,
        "salary_max": 150000,
        "salary_currency": "SGD",
        "salary_period": "annual",
        "normalized_skills": ["Python", "FastAPI", "Kubernetes", "AWS", "CI/CD", "System Design"],
        "core_skills": ["Python", "Kubernetes", "AWS", "System Design"],
        "preferred_skills": ["FastAPI", "CI/CD", "AI Orchestration"],
        "description_summary": "Own backend platform architecture, cloud reliability, and developer tooling.",
        "source": "seed",
        "source_url": "https://example.com/jobs/seed-backend-2",
    },
    {
        "external_id": "seed-data-1",
        "title": "Data Analyst",
        "role_name": "Data Analyst",
        "company_name": "Signal Metrics",
        "company_size": "mid_market",
        "company_type": "services",
        "locations": ["Singapore"],
        "work_arrangement": "hybrid",
        "job_type": "full_time",
        "industries": ["financial_services"],
        "seniority_level": "junior",
        "years_experience_min": 1,
        "years_experience_max": 3,
        "salary_min": 60000,
        "salary_max": 80000,
        "salary_currency": "SGD",
        "salary_period": "annual",
        "normalized_skills": ["SQL", "Python", "Pandas", "Tableau", "Experiment Design"],
        "core_skills": ["SQL", "Pandas", "Tableau"],
        "preferred_skills": ["Python", "Experiment Design"],
        "description_summary": "Analyze product and business data and build stakeholder dashboards.",
        "source": "seed",
        "source_url": "https://example.com/jobs/seed-data-1",
    },
    {
        "external_id": "seed-pm-1",
        "title": "AI Product Manager",
        "role_name": "Product Manager",
        "company_name": "Nova Assist",
        "company_size": "startup",
        "company_type": "product",
        "locations": ["Remote"],
        "work_arrangement": "remote",
        "job_type": "full_time",
        "industries": ["technology"],
        "seniority_level": "mid",
        "years_experience_min": 3,
        "years_experience_max": 6,
        "salary_min": 95000,
        "salary_max": 130000,
        "salary_currency": "USD",
        "salary_period": "annual",
        "normalized_skills": ["Communication", "Experiment Design", "Prompt Engineering", "AI Orchestration"],
        "core_skills": ["Communication", "Experiment Design"],
        "preferred_skills": ["Prompt Engineering", "AI Orchestration", "SQL"],
        "description_summary": "Lead AI product discovery, experimentation, and cross-functional delivery.",
        "source": "seed",
        "source_url": "https://example.com/jobs/seed-pm-1",
    },
]


def seed_job_catalog() -> None:
    existing = db.session.scalar(select(NormalizedJobPosting.id).limit(1))
    if existing:
        return

    for item in JOB_CATALOG:
        job = NormalizedJobPosting(
            external_id=item["external_id"],
            title=item["title"],
            role_key=role_key(item["role_name"]),
            role_name=item["role_name"],
            company_name=item["company_name"],
            company_size=item["company_size"],
            company_type=item["company_type"],
            locations=item["locations"],
            work_arrangement=item["work_arrangement"],
            job_type=item["job_type"],
            industries=item["industries"],
            seniority_level=item["seniority_level"],
            years_experience_min=item["years_experience_min"],
            years_experience_max=item["years_experience_max"],
            salary_min=item["salary_min"],
            salary_max=item["salary_max"],
            salary_currency=item["salary_currency"],
            salary_period=item["salary_period"],
            normalized_skills=item["normalized_skills"],
            core_skills=item["core_skills"],
            preferred_skills=item["preferred_skills"],
            description_summary=item["description_summary"],
            source=item["source"],
            source_url=item["source_url"],
            metadata_json={"seeded": True},
        )
        db.session.add(job)

    db.session.commit()
